### ISSUE TITLE
getting panic on wrong expression

### ISSUE THREAD

**Issue by Shareed2k** [ohler55/ojg#30]
i'm getting panic on bad jsonpath expression  syntax: `$[*].{}`, expecting to get error not panic :)

json example: 
```json
[
  {
    "Name": "sds-sds",
    "BackendName": "sd",
    "ID": "i-0sdsd44c0",
    "PublicIP": "23.23.23.23",
    "PrivateIP": "12.12.2.2",
    "Status": "Running",
    "Type": "r5d.large"
  }
]
```

```golang
// example of struct
type Instance struct {
  ID          string
  BackendName string
  Name        string
  Type        string
  Status      string
  PrivateIP   string
  PublicIP    string
}

items := make([]*Instance, 0)

...

expr, err := jp.ParseString("$[*].{}")
if err != nil {
	return err
}

out, err := oj.Marshal(items), &oj.Options{Indent: 2, KeyExact: true})
if err != nil {
	return err
}
```

```bash
panic: reflect: call of reflect.Value.CanInterface on zero Value

goroutine 1 [running]:
reflect.Value.CanInterface(...)
        /usr/local/opt/go/libexec/src/reflect/value.go:1005
github.com/ohler55/ojg/jp.Expr.reflectGetChild(0xc0004f22c0, 0x3, 0x4, 0x2f01e60, 0xc0004e43f0, 0xc000494878, 0x2, 0x4, 0x2e6760f, 0x4)
        /Users/shareed2k/go-workspace/pkg/mod/github.com/ohler55/ojg@v1.4.1/jp/get.go:1145 +0x38d
github.com/ohler55/ojg/jp.Expr.Get(0xc0004f22c0, 0x3, 0x4, 0x3102880, 0xc0004db700, 0x4, 0x0, 0x0)
        /Users/shareed2k/go-workspace/pkg/mod/github.com/ohler55/ojg@v1.4.1/jp/get.go:66 +0x66fe
github.com/shareed2k/honey/pkg/place/printers.Print(0xc00035fca0, 0x4, 0x4)
        /Users/shareed2k/golang_projects/honey/pkg/place/printers/printer.go:61 +0x759
github.com/shareed2k/honey/pkg/place/operations.Find(0x370d060, 0xc0000520a0, 0xc0004db440, 0x2, 0x2, 0x7ffeefbff1ed, 0x5, 0x0, 0x7ffeefbff1f5, 0x10, ...)
        /Users/shareed2k/golang_projects/honey/pkg/place/operations/find.go:75 +0x2d2
github.com/shareed2k/honey/cmd.glob..func1(0x441e5a0, 0xc000443d60, 0x0, 0x5, 0x0, 0x0)
        /Users/shareed2k/golang_projects/honey/cmd/root.go:44 +0xad
github.com/spf13/cobra.(*Command).execute(0x441e5a0, 0xc00004e250, 0x5, 0x5, 0x441e5a0, 0xc00004e250)
        /Users/shareed2k/go-workspace/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x441e5a0, 0x1046ab7, 0x43b0c80, 0xc000000180)
        /Users/shareed2k/go-workspace/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/shareed2k/go-workspace/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/shareed2k/honey/cmd.Execute()
        /Users/shareed2k/golang_projects/honey/cmd/root.go:53 +0x3b
main.main()
        /Users/shareed2k/golang_projects/honey/main.go:10 +0x25
```

**Comment by ohler55** [comment]
The `{}` is not valid syntax but there should not be a panic. I'll get that fixed right away.

**Comment by ohler55** [comment]
I wasn't sure what the code above was trying to do but after some trial and error on the pieces you had I can up with a unit test that does panic. On the way to fixing it now. The test is:

``` golang
	type Instance struct {
		ID          string
		BackendName string
		Name        string
		Type        string
		Status      string
		PrivateIP   string
		PublicIP    string
	}
	items := []*Instance{
		{
			Name:        "sds-sds",
			BackendName: "sd",
			ID:          "i-0sdsd44c0",
			PublicIP:    "23.23.23.23",
			PrivateIP:   "12.12.2.2",
			Status:      "Running",
			Type:        "r5d.large",
		},
	}
	expr, err := jp.ParseString("$[*].{}")
	tt.Nil(t, err)
	_ = oj.JSON(expr.Get(items))
```

**Comment by ohler55** [comment]
Fixed in branch bug/get-nothing. Please give it a try and I will make a release if you don't have any problem with the branch.

**Comment by Shareed2k** [comment]
now if i will try to pass invalid syntax `$[*].{.dfs}sd33434` it should return error? cause now it just return an empty json array ?

**Comment by ohler55** [comment]
So that path when broken down is any array element on root followed by a object entry with a key of `{` which is then followed by a key of `dfs}sd33434`. The path implementation allows '{' and '}'. I had to double check to confirm that in the code. If you are using the resultant path expression there are no matches in your data and an empty slice is returned.

What call are you making that you expect and error from?

**Comment by Shareed2k** [comment]
ok never mind, all good now, another question not related to this issue, there any way to add flag to lower case the keys or maybe some hook function  to transform keys ?

**Comment by ohler55** [comment]
Do you mean to make the path search be case insensitive? That might be a nice option if that is what you mean. Or do you mean to have code that modifies JSON to make all keys lowercase?

**Comment by Shareed2k** [comment]
yes I mean to modify all json keys to lowercase

**Comment by ohler55** [comment]
That's not really something that belongs in OjG but if you would like some code to do that I would be glad to put together a simple function to do that.

**Comment by ohler55** [comment]
There is most likely room for improvement but this should change a parsed JSON into all lower case keys:

``` golang
func lower(val interface{}) {
	switch tv := val.(type) {
	case map[string]interface{}:
		for k, v := range tv {
			lower(v)
			lo := strings.ToLower(k)
			if lo == k {
				continue
			}
			delete(tv, k)
			tv[lo] = v
		}
	case []interface{}:
		for _, v := range tv {
			lower(v)
		}
	}
}
```

**Comment by ohler55** [comment]
Can this be closed?

**Comment by Shareed2k** [comment]
Yes please

**Comment by Shareed2k** [comment]
Thank you
